// scripts/lib/iso-3166-2.cjs
'use strict';

// A project-maintained allowlist of ISO 3166-2 subdivision codes for the
// jurisdictions the Research Center currently supports.
//
// WHY THIS EXISTS. The previous check was structural only: it verified that a
// code LOOKED like "XX-YYY" and nothing more, so `GB-ZZZ` passed, and so did
// `GB-EAW`. GB-EAW is not an ISO 3166-2 subdivision — it is a deprecated
// compound identifier that ISO once listed as supplementary material "for
// completeness", which Unicode CLDR marks deprecated and still carries a
// display name for. That display name is why the code looks real in downstream
// libraries, and it is exactly how a fake code reaches a dataset that claims
// ISO validation. A format check cannot catch that. An allowlist can.
//
// SCOPE, STATED HONESTLY. This is NOT the complete ISO 3166-2 register. It
// covers 9 countries — US, CA, AU, DE, ES, IT, JP, CN, GB — being those the section
// publishes for or is preparing to publish for. Extending it to a new country
// is a deliberate act: regenerate from the source below and review the diff.
//
// PROVENANCE. Generated from the Debian `iso-codes` project's iso_3166-2.json,
// an ISO-derived dataset whose maintenance agency is ISO itself. Fetched
// 2026-08-05; SHA-256 of the source file:
//   78c90ef7fc25b5c2631aac5f089bc9ff6ec22c025c05b6ddbc087a1f1be2e46a
// Corroborated against Unicode CLDR's subdivision validity data (GB-ENG, GB-SCT
// and GB-WLS are category Country; GB-NIR is Province; GB-EAW, GB-GBN and
// GB-UKM appear only in CLDR's *deprecated* block) and against the GOV.UK
// open-standards country-codes publication, which endorses only GB-ENG, GB-NIR,
// GB-SCT and GB-WLS (or GB-CYM) for the United Kingdom.
//
// NO I/O. This module reads nothing and fetches nothing, at runtime or at build
// time. The generator that wrote it is not part of the build.
//
// NOT IN HERE, DELIBERATELY. org-id.guide organisation prefixes (GB-CHC for the
// Charity Commission, GB-COH for Companies House), Companies House numbers,
// charity registration numbers and internal database codes all share the
// "GB-" shape and none is an ISO 3166-2 subdivision. See DEPRECATED_OR_FOREIGN.

// [code, ISO subdivision category, ISO name]
const SUBDIVISIONS = {
  US: [
    ['US-AK', "State", "Alaska"],
    ['US-AL', "State", "Alabama"],
    ['US-AR', "State", "Arkansas"],
    ['US-AS', "Outlying area", "American Samoa"],
    ['US-AZ', "State", "Arizona"],
    ['US-CA', "State", "California"],
    ['US-CO', "State", "Colorado"],
    ['US-CT', "State", "Connecticut"],
    ['US-DC', "District", "District of Columbia"],
    ['US-DE', "State", "Delaware"],
    ['US-FL', "State", "Florida"],
    ['US-GA', "State", "Georgia"],
    ['US-GU', "Outlying area", "Guam"],
    ['US-HI', "State", "Hawaii"],
    ['US-IA', "State", "Iowa"],
    ['US-ID', "State", "Idaho"],
    ['US-IL', "State", "Illinois"],
    ['US-IN', "State", "Indiana"],
    ['US-KS', "State", "Kansas"],
    ['US-KY', "State", "Kentucky"],
    ['US-LA', "State", "Louisiana"],
    ['US-MA', "State", "Massachusetts"],
    ['US-MD', "State", "Maryland"],
    ['US-ME', "State", "Maine"],
    ['US-MI', "State", "Michigan"],
    ['US-MN', "State", "Minnesota"],
    ['US-MO', "State", "Missouri"],
    ['US-MP', "Outlying area", "Northern Mariana Islands"],
    ['US-MS', "State", "Mississippi"],
    ['US-MT', "State", "Montana"],
    ['US-NC', "State", "North Carolina"],
    ['US-ND', "State", "North Dakota"],
    ['US-NE', "State", "Nebraska"],
    ['US-NH', "State", "New Hampshire"],
    ['US-NJ', "State", "New Jersey"],
    ['US-NM', "State", "New Mexico"],
    ['US-NV', "State", "Nevada"],
    ['US-NY', "State", "New York"],
    ['US-OH', "State", "Ohio"],
    ['US-OK', "State", "Oklahoma"],
    ['US-OR', "State", "Oregon"],
    ['US-PA', "State", "Pennsylvania"],
    ['US-PR', "Outlying area", "Puerto Rico"],
    ['US-RI', "State", "Rhode Island"],
    ['US-SC', "State", "South Carolina"],
    ['US-SD', "State", "South Dakota"],
    ['US-TN', "State", "Tennessee"],
    ['US-TX', "State", "Texas"],
    ['US-UM', "Outlying area", "United States Minor Outlying Islands"],
    ['US-UT', "State", "Utah"],
    ['US-VA', "State", "Virginia"],
    ['US-VI', "Outlying area", "Virgin Islands, U.S."],
    ['US-VT', "State", "Vermont"],
    ['US-WA', "State", "Washington"],
    ['US-WI', "State", "Wisconsin"],
    ['US-WV', "State", "West Virginia"],
    ['US-WY', "State", "Wyoming"],
  ],
  CA: [
    ['CA-AB', "Province", "Alberta"],
    ['CA-BC', "Province", "British Columbia"],
    ['CA-MB', "Province", "Manitoba"],
    ['CA-NB', "Province", "New Brunswick"],
    ['CA-NL', "Province", "Newfoundland and Labrador"],
    ['CA-NS', "Province", "Nova Scotia"],
    ['CA-NT', "Territory", "Northwest Territories"],
    ['CA-NU', "Territory", "Nunavut"],
    ['CA-ON', "Province", "Ontario"],
    ['CA-PE', "Province", "Prince Edward Island"],
    ['CA-QC', "Province", "Quebec"],
    ['CA-SK', "Province", "Saskatchewan"],
    ['CA-YT', "Territory", "Yukon"],
  ],
  AU: [
    ['AU-ACT', "Territory", "Australian Capital Territory"],
    ['AU-NSW', "State", "New South Wales"],
    ['AU-NT', "Territory", "Northern Territory"],
    ['AU-QLD', "State", "Queensland"],
    ['AU-SA', "State", "South Australia"],
    ['AU-TAS', "State", "Tasmania"],
    ['AU-VIC', "State", "Victoria"],
    ['AU-WA', "State", "Western Australia"],
  ],
  DE: [
    ['DE-BB', "Land", "Brandenburg"],
    ['DE-BE', "Land", "Berlin"],
    ['DE-BW', "Land", "Baden-Württemberg"],
    ['DE-BY', "Land", "Bayern"],
    ['DE-HB', "Land", "Bremen"],
    ['DE-HE', "Land", "Hessen"],
    ['DE-HH', "Land", "Hamburg"],
    ['DE-MV', "Land", "Mecklenburg-Vorpommern"],
    ['DE-NI', "Land", "Niedersachsen"],
    ['DE-NW', "Land", "Nordrhein-Westfalen"],
    ['DE-RP', "Land", "Rheinland-Pfalz"],
    ['DE-SH', "Land", "Schleswig-Holstein"],
    ['DE-SL', "Land", "Saarland"],
    ['DE-SN', "Land", "Sachsen"],
    ['DE-ST', "Land", "Sachsen-Anhalt"],
    ['DE-TH', "Land", "Thüringen"],
  ],
  ES: [
    ['ES-A', "Province", "Alicante"],
    ['ES-AB', "Province", "Albacete"],
    ['ES-AL', "Province", "Almería"],
    ['ES-AN', "Autonomous community", "Andalucía"],
    ['ES-AR', "Autonomous community", "Aragón"],
    ['ES-AS', "Autonomous community", "Asturias, Principado de"],
    ['ES-AV', "Province", "Ávila"],
    ['ES-B', "Province", "Barcelona [Barcelona]"],
    ['ES-BA', "Province", "Badajoz"],
    ['ES-BI', "Province", "Bizkaia"],
    ['ES-BU', "Province", "Burgos"],
    ['ES-C', "Province", "A Coruña [La Coruña]"],
    ['ES-CA', "Province", "Cádiz"],
    ['ES-CB', "Autonomous community", "Cantabria"],
    ['ES-CC', "Province", "Cáceres"],
    ['ES-CE', "Autonomous city in north africa", "Ceuta"],
    ['ES-CL', "Autonomous community", "Castilla y León"],
    ['ES-CM', "Autonomous community", "Castilla-La Mancha"],
    ['ES-CN', "Autonomous community", "Canarias"],
    ['ES-CO', "Province", "Córdoba"],
    ['ES-CR', "Province", "Ciudad Real"],
    ['ES-CS', "Province", "Castellón"],
    ['ES-CT', "Autonomous community", "Catalunya [Cataluña]"],
    ['ES-CU', "Province", "Cuenca"],
    ['ES-EX', "Autonomous community", "Extremadura"],
    ['ES-GA', "Autonomous community", "Galicia [Galicia]"],
    ['ES-GC', "Province", "Las Palmas"],
    ['ES-GI', "Province", "Girona [Gerona]"],
    ['ES-GR', "Province", "Granada"],
    ['ES-GU', "Province", "Guadalajara"],
    ['ES-H', "Province", "Huelva"],
    ['ES-HU', "Province", "Huesca"],
    ['ES-IB', "Autonomous community", "Illes Balears [Islas Baleares]"],
    ['ES-J', "Province", "Jaén"],
    ['ES-L', "Province", "Lleida [Lérida]"],
    ['ES-LE', "Province", "León"],
    ['ES-LO', "Province", "La Rioja"],
    ['ES-LU', "Province", "Lugo [Lugo]"],
    ['ES-M', "Province", "Madrid"],
    ['ES-MA', "Province", "Málaga"],
    ['ES-MC', "Autonomous community", "Murcia, Región de"],
    ['ES-MD', "Autonomous community", "Madrid, Comunidad de"],
    ['ES-ML', "Autonomous city in north africa", "Melilla"],
    ['ES-MU', "Province", "Murcia"],
    ['ES-NA', "Province", "Navarra"],
    ['ES-NC', "Autonomous community", "Navarra, Comunidad Foral de"],
    ['ES-O', "Province", "Asturias"],
    ['ES-OR', "Province", "Ourense [Orense]"],
    ['ES-P', "Province", "Palencia"],
    ['ES-PM', "Province", "Illes Balears [Islas Baleares]"],
    ['ES-PO', "Province", "Pontevedra [Pontevedra]"],
    ['ES-PV', "Autonomous community", "País Vasco"],
    ['ES-RI', "Autonomous community", "La Rioja"],
    ['ES-S', "Province", "Cantabria"],
    ['ES-SA', "Province", "Salamanca"],
    ['ES-SE', "Province", "Sevilla"],
    ['ES-SG', "Province", "Segovia"],
    ['ES-SO', "Province", "Soria"],
    ['ES-SS', "Province", "Gipuzkoa"],
    ['ES-T', "Province", "Tarragona [Tarragona]"],
    ['ES-TE', "Province", "Teruel"],
    ['ES-TF', "Province", "Santa Cruz de Tenerife"],
    ['ES-TO', "Province", "Toledo"],
    ['ES-V', "Province", "Valencia"],
    ['ES-VA', "Province", "Valladolid"],
    ['ES-VC', "Autonomous community", "Valenciana, Comunidad"],
    ['ES-VI', "Province", "Álava"],
    ['ES-Z', "Province", "Zaragoza"],
    ['ES-ZA', "Province", "Zamora"],
  ],
  IT: [
    ['IT-21', "Region", "Piemonte"],
    ['IT-23', "Autonomous region", "Valle d'Aosta"],
    ['IT-25', "Region", "Lombardia"],
    ['IT-32', "Autonomous region", "Trentino-Alto Adige"],
    ['IT-34', "Region", "Veneto"],
    ['IT-36', "Autonomous region", "Friuli Venezia Giulia"],
    ['IT-42', "Region", "Liguria"],
    ['IT-45', "Region", "Emilia-Romagna"],
    ['IT-52', "Region", "Toscana"],
    ['IT-55', "Region", "Umbria"],
    ['IT-57', "Region", "Marche"],
    ['IT-62', "Region", "Lazio"],
    ['IT-65', "Region", "Abruzzo"],
    ['IT-67', "Region", "Molise"],
    ['IT-72', "Region", "Campania"],
    ['IT-75', "Region", "Puglia"],
    ['IT-77', "Region", "Basilicata"],
    ['IT-78', "Region", "Calabria"],
    ['IT-82', "Autonomous region", "Sicilia"],
    ['IT-88', "Autonomous region", "Sardegna"],
    ['IT-AG', "Free municipal consortium", "Agrigento"],
    ['IT-AL', "Province", "Alessandria"],
    ['IT-AN', "Province", "Ancona"],
    ['IT-AP', "Province", "Ascoli Piceno"],
    ['IT-AQ', "Province", "L'Aquila"],
    ['IT-AR', "Province", "Arezzo"],
    ['IT-AT', "Province", "Asti"],
    ['IT-AV', "Province", "Avellino"],
    ['IT-BA', "Metropolitan city", "Bari"],
    ['IT-BG', "Province", "Bergamo"],
    ['IT-BI', "Province", "Biella"],
    ['IT-BL', "Province", "Belluno"],
    ['IT-BN', "Province", "Benevento"],
    ['IT-BO', "Metropolitan city", "Bologna"],
    ['IT-BR', "Province", "Brindisi"],
    ['IT-BS', "Province", "Brescia"],
    ['IT-BT', "Province", "Barletta-Andria-Trani"],
    ['IT-BZ', "Autonomous province", "Bolzano"],
    ['IT-CA', "Metropolitan city", "Cagliari"],
    ['IT-CB', "Province", "Campobasso"],
    ['IT-CE', "Province", "Caserta"],
    ['IT-CH', "Province", "Chieti"],
    ['IT-CL', "Free municipal consortium", "Caltanissetta"],
    ['IT-CN', "Province", "Cuneo"],
    ['IT-CO', "Province", "Como"],
    ['IT-CR', "Province", "Cremona"],
    ['IT-CS', "Province", "Cosenza"],
    ['IT-CT', "Metropolitan city", "Catania"],
    ['IT-CZ', "Province", "Catanzaro"],
    ['IT-EN', "Free municipal consortium", "Enna"],
    ['IT-FC', "Province", "Forlì-Cesena"],
    ['IT-FE', "Province", "Ferrara"],
    ['IT-FG', "Province", "Foggia"],
    ['IT-FI', "Metropolitan city", "Firenze"],
    ['IT-FM', "Province", "Fermo"],
    ['IT-FR', "Province", "Frosinone"],
    ['IT-GE', "Metropolitan city", "Genova"],
    ['IT-GO', "Decentralized regional entity", "Gorizia"],
    ['IT-GR', "Province", "Grosseto"],
    ['IT-IM', "Province", "Imperia"],
    ['IT-IS', "Province", "Isernia"],
    ['IT-KR', "Province", "Crotone"],
    ['IT-LC', "Province", "Lecco"],
    ['IT-LE', "Province", "Lecce"],
    ['IT-LI', "Province", "Livorno"],
    ['IT-LO', "Province", "Lodi"],
    ['IT-LT', "Province", "Latina"],
    ['IT-LU', "Province", "Lucca"],
    ['IT-MB', "Province", "Monza e Brianza"],
    ['IT-MC', "Province", "Macerata"],
    ['IT-ME', "Metropolitan city", "Messina"],
    ['IT-MI', "Metropolitan city", "Milano"],
    ['IT-MN', "Province", "Mantova"],
    ['IT-MO', "Province", "Modena"],
    ['IT-MS', "Province", "Massa-Carrara"],
    ['IT-MT', "Province", "Matera"],
    ['IT-NA', "Metropolitan city", "Napoli"],
    ['IT-NO', "Province", "Novara"],
    ['IT-NU', "Province", "Nuoro"],
    ['IT-OR', "Province", "Oristano"],
    ['IT-PA', "Metropolitan city", "Palermo"],
    ['IT-PC', "Province", "Piacenza"],
    ['IT-PD', "Province", "Padova"],
    ['IT-PE', "Province", "Pescara"],
    ['IT-PG', "Province", "Perugia"],
    ['IT-PI', "Province", "Pisa"],
    ['IT-PN', "Decentralized regional entity", "Pordenone"],
    ['IT-PO', "Province", "Prato"],
    ['IT-PR', "Province", "Parma"],
    ['IT-PT', "Province", "Pistoia"],
    ['IT-PU', "Province", "Pesaro e Urbino"],
    ['IT-PV', "Province", "Pavia"],
    ['IT-PZ', "Province", "Potenza"],
    ['IT-RA', "Province", "Ravenna"],
    ['IT-RC', "Metropolitan city", "Reggio Calabria"],
    ['IT-RE', "Province", "Reggio Emilia"],
    ['IT-RG', "Free municipal consortium", "Ragusa"],
    ['IT-RI', "Province", "Rieti"],
    ['IT-RM', "Metropolitan city", "Roma"],
    ['IT-RN', "Province", "Rimini"],
    ['IT-RO', "Province", "Rovigo"],
    ['IT-SA', "Province", "Salerno"],
    ['IT-SI', "Province", "Siena"],
    ['IT-SO', "Province", "Sondrio"],
    ['IT-SP', "Province", "La Spezia"],
    ['IT-SR', "Free municipal consortium", "Siracusa"],
    ['IT-SS', "Province", "Sassari"],
    ['IT-SU', "Province", "Sud Sardegna"],
    ['IT-SV', "Province", "Savona"],
    ['IT-TA', "Province", "Taranto"],
    ['IT-TE', "Province", "Teramo"],
    ['IT-TN', "Autonomous province", "Trento"],
    ['IT-TO', "Metropolitan city", "Torino"],
    ['IT-TP', "Free municipal consortium", "Trapani"],
    ['IT-TR', "Province", "Terni"],
    ['IT-TS', "Decentralized regional entity", "Trieste"],
    ['IT-TV', "Province", "Treviso"],
    ['IT-UD', "Decentralized regional entity", "Udine"],
    ['IT-VA', "Province", "Varese"],
    ['IT-VB', "Province", "Verbano-Cusio-Ossola"],
    ['IT-VC', "Province", "Vercelli"],
    ['IT-VE', "Metropolitan city", "Venezia"],
    ['IT-VI', "Province", "Vicenza"],
    ['IT-VR', "Province", "Verona"],
    ['IT-VT', "Province", "Viterbo"],
    ['IT-VV', "Province", "Vibo Valentia"],
  ],
  JP: [
    ['JP-01', "Prefecture", "Hokkaido"],
    ['JP-02', "Prefecture", "Aomori"],
    ['JP-03', "Prefecture", "Iwate"],
    ['JP-04', "Prefecture", "Miyagi"],
    ['JP-05', "Prefecture", "Akita"],
    ['JP-06', "Prefecture", "Yamagata"],
    ['JP-07', "Prefecture", "Fukushima"],
    ['JP-08', "Prefecture", "Ibaraki"],
    ['JP-09', "Prefecture", "Tochigi"],
    ['JP-10', "Prefecture", "Gunma"],
    ['JP-11', "Prefecture", "Saitama"],
    ['JP-12', "Prefecture", "Chiba"],
    ['JP-13', "Prefecture", "Tokyo"],
    ['JP-14', "Prefecture", "Kanagawa"],
    ['JP-15', "Prefecture", "Niigata"],
    ['JP-16', "Prefecture", "Toyama"],
    ['JP-17', "Prefecture", "Ishikawa"],
    ['JP-18', "Prefecture", "Fukui"],
    ['JP-19', "Prefecture", "Yamanashi"],
    ['JP-20', "Prefecture", "Nagano"],
    ['JP-21', "Prefecture", "Gifu"],
    ['JP-22', "Prefecture", "Shizuoka"],
    ['JP-23', "Prefecture", "Aichi"],
    ['JP-24', "Prefecture", "Mie"],
    ['JP-25', "Prefecture", "Shiga"],
    ['JP-26', "Prefecture", "Kyoto"],
    ['JP-27', "Prefecture", "Osaka"],
    ['JP-28', "Prefecture", "Hyogo"],
    ['JP-29', "Prefecture", "Nara"],
    ['JP-30', "Prefecture", "Wakayama"],
    ['JP-31', "Prefecture", "Tottori"],
    ['JP-32', "Prefecture", "Shimane"],
    ['JP-33', "Prefecture", "Okayama"],
    ['JP-34', "Prefecture", "Hiroshima"],
    ['JP-35', "Prefecture", "Yamaguchi"],
    ['JP-36', "Prefecture", "Tokushima"],
    ['JP-37', "Prefecture", "Kagawa"],
    ['JP-38', "Prefecture", "Ehime"],
    ['JP-39', "Prefecture", "Kochi"],
    ['JP-40', "Prefecture", "Fukuoka"],
    ['JP-41', "Prefecture", "Saga"],
    ['JP-42', "Prefecture", "Nagasaki"],
    ['JP-43', "Prefecture", "Kumamoto"],
    ['JP-44', "Prefecture", "Oita"],
    ['JP-45', "Prefecture", "Miyazaki"],
    ['JP-46', "Prefecture", "Kagoshima"],
    ['JP-47', "Prefecture", "Okinawa"],
  ],
  CN: [
    ['CN-AH', "Province", "Anhui Sheng"],
    ['CN-BJ', "Municipality", "Beijing Shi"],
    ['CN-CQ', "Municipality", "Chongqing Shi"],
    ['CN-FJ', "Province", "Fujian Sheng"],
    ['CN-GD', "Province", "Guangdong Sheng"],
    ['CN-GS', "Province", "Gansu Sheng"],
    ['CN-GX', "Autonomous region", "Guangxi Zhuangzu Zizhiqu"],
    ['CN-GZ', "Province", "Guizhou Sheng"],
    ['CN-HA', "Province", "Henan Sheng"],
    ['CN-HB', "Province", "Hubei Sheng"],
    ['CN-HE', "Province", "Hebei Sheng"],
    ['CN-HI', "Province", "Hainan Sheng"],
    ['CN-HK', "Special administrative region", "Hong Kong SAR"],
    ['CN-HL', "Province", "Heilongjiang Sheng"],
    ['CN-HN', "Province", "Hunan Sheng"],
    ['CN-JL', "Province", "Jilin Sheng"],
    ['CN-JS', "Province", "Jiangsu Sheng"],
    ['CN-JX', "Province", "Jiangxi Sheng"],
    ['CN-LN', "Province", "Liaoning Sheng"],
    ['CN-MO', "Special administrative region", "Macao SAR"],
    ['CN-NM', "Autonomous region", "Nei Mongol Zizhiqu"],
    ['CN-NX', "Autonomous region", "Ningxia Huizu Zizhiqu"],
    ['CN-QH', "Province", "Qinghai Sheng"],
    ['CN-SC', "Province", "Sichuan Sheng"],
    ['CN-SD', "Province", "Shandong Sheng"],
    ['CN-SH', "Municipality", "Shanghai Shi"],
    ['CN-SN', "Province", "Shaanxi Sheng"],
    ['CN-SX', "Province", "Shanxi Sheng"],
    ['CN-TJ', "Municipality", "Tianjin Shi"],
    ['CN-TW', "Province", "Taiwan Sheng"],
    ['CN-XJ', "Autonomous region", "Xinjiang Uygur Zizhiqu"],
    ['CN-XZ', "Autonomous region", "Xizang Zizhiqu"],
    ['CN-YN', "Province", "Yunnan Sheng"],
    ['CN-ZJ', "Province", "Zhejiang Sheng"],
  ],
  GB: [
    ['GB-ABC', "District", "Armagh City, Banbridge and Craigavon"],
    ['GB-ABD', "Council area", "Aberdeenshire"],
    ['GB-ABE', "Council area", "Aberdeen City"],
    ['GB-AGB', "Council area", "Argyll and Bute"],
    ['GB-AGY', "Unitary authority", "Isle of Anglesey [Sir Ynys Môn GB-YNM]"],
    ['GB-AND', "District", "Ards and North Down"],
    ['GB-ANN', "District", "Antrim and Newtownabbey"],
    ['GB-ANS', "Council area", "Angus"],
    ['GB-BAS', "Unitary authority", "Bath and North East Somerset"],
    ['GB-BBD', "Unitary authority", "Blackburn with Darwen"],
    ['GB-BCP', "Unitary authority", "Bournemouth, Christchurch and Poole"],
    ['GB-BDF', "Unitary authority", "Bedford"],
    ['GB-BDG', "London borough", "Barking and Dagenham"],
    ['GB-BEN', "London borough", "Brent"],
    ['GB-BEX', "London borough", "Bexley"],
    ['GB-BFS', "District", "Belfast City"],
    ['GB-BGE', "Unitary authority", "Bridgend [Pen-y-bont ar Ogwr GB-POG]"],
    ['GB-BGW', "Unitary authority", "Blaenau Gwent"],
    ['GB-BIR', "Metropolitan district", "Birmingham"],
    ['GB-BKM', "Unitary authority", "Buckinghamshire"],
    ['GB-BNE', "London borough", "Barnet"],
    ['GB-BNH', "Unitary authority", "Brighton and Hove"],
    ['GB-BNS', "Metropolitan district", "Barnsley"],
    ['GB-BOL', "Metropolitan district", "Bolton"],
    ['GB-BPL', "Unitary authority", "Blackpool"],
    ['GB-BRC', "Unitary authority", "Bracknell Forest"],
    ['GB-BRD', "Metropolitan district", "Bradford"],
    ['GB-BRY', "London borough", "Bromley"],
    ['GB-BST', "Unitary authority", "Bristol, City of"],
    ['GB-BUR', "Metropolitan district", "Bury"],
    ['GB-CAM', "Two-tier county", "Cambridgeshire"],
    ['GB-CAY', "Unitary authority", "Caerphilly [Caerffili GB-CAF]"],
    ['GB-CBF', "Unitary authority", "Central Bedfordshire"],
    ['GB-CCG', "District", "Causeway Coast and Glens"],
    ['GB-CGN', "Unitary authority", "Ceredigion [Sir Ceredigion]"],
    ['GB-CHE', "Unitary authority", "Cheshire East"],
    ['GB-CHW', "Unitary authority", "Cheshire West and Chester"],
    ['GB-CLD', "Metropolitan district", "Calderdale"],
    ['GB-CLK', "Council area", "Clackmannanshire"],
    ['GB-CMA', "Two-tier county", "Cumbria"],
    ['GB-CMD', "London borough", "Camden"],
    ['GB-CMN', "Unitary authority", "Carmarthenshire [Sir Gaerfyrddin GB-GFY]"],
    ['GB-CON', "Unitary authority", "Cornwall"],
    ['GB-COV', "Metropolitan district", "Coventry"],
    ['GB-CRF', "Unitary authority", "Cardiff [Caerdydd GB-CRD]"],
    ['GB-CRY', "London borough", "Croydon"],
    ['GB-CWY', "Unitary authority", "Conwy"],
    ['GB-DAL', "Unitary authority", "Darlington"],
    ['GB-DBY', "Two-tier county", "Derbyshire"],
    ['GB-DEN', "Unitary authority", "Denbighshire [Sir Ddinbych GB-DDB]"],
    ['GB-DER', "Unitary authority", "Derby"],
    ['GB-DEV', "Two-tier county", "Devon"],
    ['GB-DGY', "Council area", "Dumfries and Galloway"],
    ['GB-DNC', "Metropolitan district", "Doncaster"],
    ['GB-DND', "Council area", "Dundee City"],
    ['GB-DOR', "Two-tier county", "Dorset"],
    ['GB-DRS', "District", "Derry and Strabane"],
    ['GB-DUD', "Metropolitan district", "Dudley"],
    ['GB-DUR', "Unitary authority", "Durham, County"],
    ['GB-EAL', "London borough", "Ealing"],
    ['GB-EAY', "Council area", "East Ayrshire"],
    ['GB-EDH', "Council area", "Edinburgh, City of"],
    ['GB-EDU', "Council area", "East Dunbartonshire"],
    ['GB-ELN', "Council area", "East Lothian"],
    ['GB-ELS', "Council area", "Eilean Siar"],
    ['GB-ENF', "London borough", "Enfield"],
    ['GB-ENG', "Country", "England"],
    ['GB-ERW', "Council area", "East Renfrewshire"],
    ['GB-ERY', "Unitary authority", "East Riding of Yorkshire"],
    ['GB-ESS', "Two-tier county", "Essex"],
    ['GB-ESX', "Two-tier county", "East Sussex"],
    ['GB-FAL', "Council area", "Falkirk"],
    ['GB-FIF', "Council area", "Fife"],
    ['GB-FLN', "Unitary authority", "Flintshire [Sir y Fflint GB-FFL]"],
    ['GB-FMO', "District", "Fermanagh and Omagh"],
    ['GB-GAT', "Metropolitan district", "Gateshead"],
    ['GB-GLG', "Council area", "Glasgow City"],
    ['GB-GLS', "Two-tier county", "Gloucestershire"],
    ['GB-GRE', "London borough", "Greenwich"],
    ['GB-GWN', "Unitary authority", "Gwynedd"],
    ['GB-HAL', "Unitary authority", "Halton"],
    ['GB-HAM', "Two-tier county", "Hampshire"],
    ['GB-HAV', "London borough", "Havering"],
    ['GB-HCK', "London borough", "Hackney"],
    ['GB-HEF', "Unitary authority", "Herefordshire"],
    ['GB-HIL', "London borough", "Hillingdon"],
    ['GB-HLD', "Council area", "Highland"],
    ['GB-HMF', "London borough", "Hammersmith and Fulham"],
    ['GB-HNS', "London borough", "Hounslow"],
    ['GB-HPL', "Unitary authority", "Hartlepool"],
    ['GB-HRT', "Two-tier county", "Hertfordshire"],
    ['GB-HRW', "London borough", "Harrow"],
    ['GB-HRY', "London borough", "Haringey"],
    ['GB-IOS', "Unitary authority", "Isles of Scilly"],
    ['GB-IOW', "Unitary authority", "Isle of Wight"],
    ['GB-ISL', "London borough", "Islington"],
    ['GB-IVC', "Council area", "Inverclyde"],
    ['GB-KEC', "London borough", "Kensington and Chelsea"],
    ['GB-KEN', "Two-tier county", "Kent"],
    ['GB-KHL', "Unitary authority", "Kingston upon Hull"],
    ['GB-KIR', "Metropolitan district", "Kirklees"],
    ['GB-KTT', "London borough", "Kingston upon Thames"],
    ['GB-KWL', "Metropolitan district", "Knowsley"],
    ['GB-LAN', "Two-tier county", "Lancashire"],
    ['GB-LBC', "District", "Lisburn and Castlereagh"],
    ['GB-LBH', "London borough", "Lambeth"],
    ['GB-LCE', "Unitary authority", "Leicester"],
    ['GB-LDS', "Metropolitan district", "Leeds"],
    ['GB-LEC', "Two-tier county", "Leicestershire"],
    ['GB-LEW', "London borough", "Lewisham"],
    ['GB-LIN', "Two-tier county", "Lincolnshire"],
    ['GB-LIV', "Metropolitan district", "Liverpool"],
    ['GB-LND', "City corporation", "London, City of"],
    ['GB-LUT', "Unitary authority", "Luton"],
    ['GB-MAN', "Metropolitan district", "Manchester"],
    ['GB-MDB', "Unitary authority", "Middlesbrough"],
    ['GB-MDW', "Unitary authority", "Medway"],
    ['GB-MEA', "District", "Mid and East Antrim"],
    ['GB-MIK', "Unitary authority", "Milton Keynes"],
    ['GB-MLN', "Council area", "Midlothian"],
    ['GB-MON', "Unitary authority", "Monmouthshire [Sir Fynwy GB-FYN]"],
    ['GB-MRT', "London borough", "Merton"],
    ['GB-MRY', "Council area", "Moray"],
    ['GB-MTY', "Unitary authority", "Merthyr Tydfil [Merthyr Tudful GB-MTU]"],
    ['GB-MUL', "District", "Mid-Ulster"],
    ['GB-NAY', "Council area", "North Ayrshire"],
    ['GB-NBL', "Unitary authority", "Northumberland"],
    ['GB-NEL', "Unitary authority", "North East Lincolnshire"],
    ['GB-NET', "Metropolitan district", "Newcastle upon Tyne"],
    ['GB-NFK', "Two-tier county", "Norfolk"],
    ['GB-NGM', "Unitary authority", "Nottingham"],
    ['GB-NIR', "Province", "Northern Ireland"],
    ['GB-NLK', "Council area", "North Lanarkshire"],
    ['GB-NLN', "Unitary authority", "North Lincolnshire"],
    ['GB-NMD', "District", "Newry, Mourne and Down"],
    ['GB-NNH', "Unitary authority", "North Northamptonshire"],
    ['GB-NSM', "Unitary authority", "North Somerset"],
    ['GB-NTL', "Unitary authority", "Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]"],
    ['GB-NTT', "Two-tier county", "Nottinghamshire"],
    ['GB-NTY', "Metropolitan district", "North Tyneside"],
    ['GB-NWM', "London borough", "Newham"],
    ['GB-NWP', "Unitary authority", "Newport [Casnewydd GB-CNW]"],
    ['GB-NYK', "Two-tier county", "North Yorkshire"],
    ['GB-OLD', "Metropolitan district", "Oldham"],
    ['GB-ORK', "Council area", "Orkney Islands"],
    ['GB-OXF', "Two-tier county", "Oxfordshire"],
    ['GB-PEM', "Unitary authority", "Pembrokeshire [Sir Benfro GB-BNF]"],
    ['GB-PKN', "Council area", "Perth and Kinross"],
    ['GB-PLY', "Unitary authority", "Plymouth"],
    ['GB-POR', "Unitary authority", "Portsmouth"],
    ['GB-POW', "Unitary authority", "Powys"],
    ['GB-PTE', "Unitary authority", "Peterborough"],
    ['GB-RCC', "Unitary authority", "Redcar and Cleveland"],
    ['GB-RCH', "Metropolitan district", "Rochdale"],
    ['GB-RCT', "Unitary authority", "Rhondda Cynon Taff [Rhondda CynonTaf]"],
    ['GB-RDB', "London borough", "Redbridge"],
    ['GB-RDG', "Unitary authority", "Reading"],
    ['GB-RFW', "Council area", "Renfrewshire"],
    ['GB-RIC', "London borough", "Richmond upon Thames"],
    ['GB-ROT', "Metropolitan district", "Rotherham"],
    ['GB-RUT', "Unitary authority", "Rutland"],
    ['GB-SAW', "Metropolitan district", "Sandwell"],
    ['GB-SAY', "Council area", "South Ayrshire"],
    ['GB-SCB', "Council area", "Scottish Borders"],
    ['GB-SCT', "Country", "Scotland"],
    ['GB-SFK', "Two-tier county", "Suffolk"],
    ['GB-SFT', "Metropolitan district", "Sefton"],
    ['GB-SGC', "Unitary authority", "South Gloucestershire"],
    ['GB-SHF', "Metropolitan district", "Sheffield"],
    ['GB-SHN', "Metropolitan district", "St. Helens"],
    ['GB-SHR', "Unitary authority", "Shropshire"],
    ['GB-SKP', "Metropolitan district", "Stockport"],
    ['GB-SLF', "Metropolitan district", "Salford"],
    ['GB-SLG', "Unitary authority", "Slough"],
    ['GB-SLK', "Council area", "South Lanarkshire"],
    ['GB-SND', "Metropolitan district", "Sunderland"],
    ['GB-SOL', "Metropolitan district", "Solihull"],
    ['GB-SOM', "Two-tier county", "Somerset"],
    ['GB-SOS', "Unitary authority", "Southend-on-Sea"],
    ['GB-SRY', "Two-tier county", "Surrey"],
    ['GB-STE', "Unitary authority", "Stoke-on-Trent"],
    ['GB-STG', "Council area", "Stirling"],
    ['GB-STH', "Unitary authority", "Southampton"],
    ['GB-STN', "London borough", "Sutton"],
    ['GB-STS', "Two-tier county", "Staffordshire"],
    ['GB-STT', "Unitary authority", "Stockton-on-Tees"],
    ['GB-STY', "Metropolitan district", "South Tyneside"],
    ['GB-SWA', "Unitary authority", "Swansea [Abertawe GB-ATA]"],
    ['GB-SWD', "Unitary authority", "Swindon"],
    ['GB-SWK', "London borough", "Southwark"],
    ['GB-TAM', "Metropolitan district", "Tameside"],
    ['GB-TFW', "Unitary authority", "Telford and Wrekin"],
    ['GB-THR', "Unitary authority", "Thurrock"],
    ['GB-TOB', "Unitary authority", "Torbay"],
    ['GB-TOF', "Unitary authority", "Torfaen [Tor-faen]"],
    ['GB-TRF', "Metropolitan district", "Trafford"],
    ['GB-TWH', "London borough", "Tower Hamlets"],
    ['GB-VGL', "Unitary authority", "Vale of Glamorgan, The [Bro Morgannwg GB-BMG]"],
    ['GB-WAR', "Two-tier county", "Warwickshire"],
    ['GB-WBK', "Unitary authority", "West Berkshire"],
    ['GB-WDU', "Council area", "West Dunbartonshire"],
    ['GB-WFT', "London borough", "Waltham Forest"],
    ['GB-WGN', "Metropolitan district", "Wigan"],
    ['GB-WIL', "Unitary authority", "Wiltshire"],
    ['GB-WKF', "Metropolitan district", "Wakefield"],
    ['GB-WLL', "Metropolitan district", "Walsall"],
    ['GB-WLN', "Council area", "West Lothian"],
    ['GB-WLS', "Country", "Wales [Cymru GB-CYM]"],
    ['GB-WLV', "Metropolitan district", "Wolverhampton"],
    ['GB-WND', "London borough", "Wandsworth"],
    ['GB-WNH', "Unitary authority", "West Northamptonshire"],
    ['GB-WNM', "Unitary authority", "Windsor and Maidenhead"],
    ['GB-WOK', "Unitary authority", "Wokingham"],
    ['GB-WOR', "Two-tier county", "Worcestershire"],
    ['GB-WRL', "Metropolitan district", "Wirral"],
    ['GB-WRT', "Unitary authority", "Warrington"],
    ['GB-WRX', "Unitary authority", "Wrexham [Wrecsam GB-WRC]"],
    ['GB-WSM', "London borough", "Westminster"],
    ['GB-WSX', "Two-tier county", "West Sussex"],
    ['GB-YOR', "Unitary authority", "York"],
    ['GB-ZET', "Council area", "Shetland Islands"],
  ],
};

// Identifiers that are structurally plausible, widely seen, and NOT ISO 3166-2
// subdivisions. Rejecting them by name lets the error say *why*, which a bare
// "not in the allowlist" cannot.
const DEPRECATED_OR_FOREIGN = {
  'GB-EAW': 'a deprecated compound entity ("England and Wales"), never an ISO 3166-2 '
    + 'subdivision — use covers: ["GB-ENG", "GB-WLS"]',
  'GB-GBN': 'a deprecated compound entity ("Great Britain"), never an ISO 3166-2 '
    + 'subdivision — use covers: ["GB-ENG", "GB-SCT", "GB-WLS"]',
  'GB-UKM': 'a deprecated compound entity ("United Kingdom"), never an ISO 3166-2 '
    + 'subdivision — a UK-wide system is scope "national" with no jurisdiction',
  'GB-CYM': 'an alternative form of GB-WLS carried inside its ISO name, not a separate '
    + 'subdivision — use GB-WLS',
  'GB-CHC': 'an org-id.guide organisation-list prefix (Charity Commission for England and '
    + 'Wales), not an ISO 3166-2 subdivision',
  'GB-COH': 'an org-id.guide organisation-list prefix (Companies House), not an ISO 3166-2 '
    + 'subdivision',
  'GB-SC': 'an org-id.guide organisation-list prefix (Scottish charity numbers), not an ISO '
    + '3166-2 subdivision — Scotland is GB-SCT',
  'GB-NIC': 'a charity-registration prefix (Charity Commission for Northern Ireland), not an '
    + 'ISO 3166-2 subdivision — Northern Ireland is GB-NIR',
};

const BY_CODE = new Map();
for (const [iso2, rows] of Object.entries(SUBDIVISIONS)) {
  for (const [code, category, name] of rows) {
    BY_CODE.set(code, { code, category, name, country: iso2 });
  }
}

const SUPPORTED_COUNTRIES = Object.freeze(Object.keys(SUBDIVISIONS));

function isKnownCode(code) {
  return BY_CODE.has(code);
}

function subdivision(code) {
  return BY_CODE.get(code) || null;
}

function countryOf(code) {
  const row = BY_CODE.get(code);
  return row ? row.country : null;
}

function codesFor(iso2) {
  const rows = SUBDIVISIONS[iso2];
  return rows ? rows.map((r) => r[0]) : null;
}

// Returns a human-readable reason the code is not usable, or null if it is.
// Ordered most-specific first so the message names the actual problem.
function unknownCodeProblem(code) {
  if (typeof code !== 'string') return `must be a string, got ${typeof code}`;
  const reason = DEPRECATED_OR_FOREIGN[code];
  if (reason) return `is ${reason}`;
  if (BY_CODE.has(code)) return null;
  const [iso2] = code.split('-');
  if (!SUBDIVISIONS[iso2]) {
    return `belongs to "${iso2}", which this allowlist does not cover `
      + `(covered: ${SUPPORTED_COUNTRIES.join(', ')}). Extend scripts/lib/iso-3166-2.cjs `
      + 'from its documented source before publishing records for it';
  }
  return `is not an ISO 3166-2 subdivision of "${iso2}". `
    + `${SUBDIVISIONS[iso2].length} are defined; check the code against the official list`;
}

module.exports = {
  SUBDIVISIONS,
  DEPRECATED_OR_FOREIGN,
  SUPPORTED_COUNTRIES,
  SOURCE_DIGEST: '78c90ef7fc25b5c2631aac5f089bc9ff6ec22c025c05b6ddbc087a1f1be2e46a',
  isKnownCode,
  subdivision,
  countryOf,
  codesFor,
  unknownCodeProblem,
};
